/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maze_swing;

/**
 *
 * @author David and Ore
 */
public class maze_jframe extends javax.swing.JFrame {

    /**
     * Creates new form maze_jframe
     */
    public maze_jframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radiobuttons_for_algos = new javax.swing.ButtonGroup();
        bottom_section_with_buttons = new javax.swing.JPanel();
        new_grid = new javax.swing.JButton();
        play = new javax.swing.JButton();
        maze1 = new javax.swing.JButton();
        clear1 = new javax.swing.JButton();
        row_spinner = new javax.swing.JSpinner();
        column_spinner = new javax.swing.JSpinner();
        row_label = new java.awt.Label();
        column_label = new java.awt.Label();
        grid_space = new javax.swing.JPanel();
        grid = new javax.swing.JLabel();
        right_panel_with_radio_buttons = new javax.swing.JPanel();
        dfs_radio_button = new javax.swing.JRadioButton();
        astar_radio_button = new javax.swing.JRadioButton();
        dijkstra = new javax.swing.JRadioButton();
        bfs_radio_button = new javax.swing.JRadioButton();
        greedy_radio_button = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 800));

        new_grid.setText("New Grid");
        new_grid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_gridActionPerformed(evt);
            }
        });

        play.setText("Play");
        play.setAutoscrolls(true);
        play.setInheritsPopupMenu(true);
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        maze1.setText("Maze");

        clear1.setText("Clear");
        clear1.setInheritsPopupMenu(true);
        clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear1ActionPerformed(evt);
            }
        });

        row_label.setText("# of rows");

        column_label.setText("# of columns");

        javax.swing.GroupLayout bottom_section_with_buttonsLayout = new javax.swing.GroupLayout(bottom_section_with_buttons);
        bottom_section_with_buttons.setLayout(bottom_section_with_buttonsLayout);
        bottom_section_with_buttonsLayout.setHorizontalGroup(
            bottom_section_with_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottom_section_with_buttonsLayout.createSequentialGroup()
                .addGroup(bottom_section_with_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bottom_section_with_buttonsLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(new_grid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61)
                        .addComponent(row_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottom_section_with_buttonsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(row_label, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGroup(bottom_section_with_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bottom_section_with_buttonsLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(column_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bottom_section_with_buttonsLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(column_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(maze1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bottom_section_with_buttonsLayout.setVerticalGroup(
            bottom_section_with_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottom_section_with_buttonsLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(bottom_section_with_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(column_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(row_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bottom_section_with_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_grid, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maze1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(row_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(column_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        new_grid.getAccessibleContext().setAccessibleName("Mew Grid");
        new_grid.getAccessibleContext().setAccessibleDescription("");

        grid_space.setBackground(new java.awt.Color(0, 0, 0));
        grid_space.setPreferredSize(new java.awt.Dimension(500, 500));

        grid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maze_swing/images/grid.png"))); // NOI18N

        javax.swing.GroupLayout grid_spaceLayout = new javax.swing.GroupLayout(grid_space);
        grid_space.setLayout(grid_spaceLayout);
        grid_spaceLayout.setHorizontalGroup(
            grid_spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grid_spaceLayout.createSequentialGroup()
                .addComponent(grid)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        grid_spaceLayout.setVerticalGroup(
            grid_spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grid_spaceLayout.createSequentialGroup()
                .addComponent(grid)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        radiobuttons_for_algos.add(dfs_radio_button);
        dfs_radio_button.setText("DFS");
        dfs_radio_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dfs_radio_buttonActionPerformed(evt);
            }
        });

        radiobuttons_for_algos.add(astar_radio_button);
        astar_radio_button.setText("A*");

        radiobuttons_for_algos.add(dijkstra);
        dijkstra.setText("Dijkstra");

        radiobuttons_for_algos.add(bfs_radio_button);
        bfs_radio_button.setText("BFS");

        radiobuttons_for_algos.add(greedy_radio_button);
        greedy_radio_button.setText("Greedy");

        javax.swing.GroupLayout right_panel_with_radio_buttonsLayout = new javax.swing.GroupLayout(right_panel_with_radio_buttons);
        right_panel_with_radio_buttons.setLayout(right_panel_with_radio_buttonsLayout);
        right_panel_with_radio_buttonsLayout.setHorizontalGroup(
            right_panel_with_radio_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(right_panel_with_radio_buttonsLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(greedy_radio_button, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(right_panel_with_radio_buttonsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(right_panel_with_radio_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(right_panel_with_radio_buttonsLayout.createSequentialGroup()
                        .addComponent(astar_radio_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(dijkstra))
                    .addGroup(right_panel_with_radio_buttonsLayout.createSequentialGroup()
                        .addComponent(dfs_radio_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bfs_radio_button)))
                .addGap(28, 28, 28))
        );
        right_panel_with_radio_buttonsLayout.setVerticalGroup(
            right_panel_with_radio_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(right_panel_with_radio_buttonsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(right_panel_with_radio_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dfs_radio_button)
                    .addComponent(bfs_radio_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(right_panel_with_radio_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(astar_radio_button)
                    .addComponent(dijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(greedy_radio_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(grid_space, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(right_panel_with_radio_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(bottom_section_with_buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(right_panel_with_radio_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(grid_space, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addComponent(bottom_section_with_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dfs_radio_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dfs_radio_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dfs_radio_buttonActionPerformed

    private void clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clear1ActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playActionPerformed

    private void new_gridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_gridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_gridActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(maze_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(maze_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(maze_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(maze_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new maze_jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton astar_radio_button;
    private javax.swing.JRadioButton bfs_radio_button;
    private javax.swing.JPanel bottom_section_with_buttons;
    private javax.swing.JButton clear1;
    private java.awt.Label column_label;
    private javax.swing.JSpinner column_spinner;
    private javax.swing.JRadioButton dfs_radio_button;
    private javax.swing.JRadioButton dijkstra;
    private javax.swing.JRadioButton greedy_radio_button;
    private javax.swing.JLabel grid;
    private javax.swing.JPanel grid_space;
    private javax.swing.JButton maze1;
    private javax.swing.JButton new_grid;
    private javax.swing.JButton play;
    private javax.swing.ButtonGroup radiobuttons_for_algos;
    private javax.swing.JPanel right_panel_with_radio_buttons;
    private java.awt.Label row_label;
    private javax.swing.JSpinner row_spinner;
    // End of variables declaration//GEN-END:variables
}
